package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HotelRoom generated by hbm2java
 */
public class HotelRoom  implements java.io.Serializable {


     private String roomId;
     private Hotel hotel;
     private String roomNum;
     private String roomType;
     private double roomPrice;
     private int isUse;
     private Set<HotelBook> hotelBooks = new HashSet<HotelBook>(0);

    public HotelRoom() {
    }

	
    public HotelRoom(String roomId, Hotel hotel, String roomNum, String roomType, double roomPrice, int isUse) {
        this.roomId = roomId;
        this.hotel = hotel;
        this.roomNum = roomNum;
        this.roomType = roomType;
        this.roomPrice = roomPrice;
        this.isUse = isUse;
    }
    public HotelRoom(String roomId, Hotel hotel, String roomNum, String roomType, double roomPrice, int isUse, Set<HotelBook> hotelBooks) {
       this.roomId = roomId;
       this.hotel = hotel;
       this.roomNum = roomNum;
       this.roomType = roomType;
       this.roomPrice = roomPrice;
       this.isUse = isUse;
       this.hotelBooks = hotelBooks;
    }
   
    public String getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getRoomNum() {
        return this.roomNum;
    }
    
    public void setRoomNum(String roomNum) {
        this.roomNum = roomNum;
    }
    public String getRoomType() {
        return this.roomType;
    }
    
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    public double getRoomPrice() {
        return this.roomPrice;
    }
    
    public void setRoomPrice(double roomPrice) {
        this.roomPrice = roomPrice;
    }
    public int getIsUse() {
        return this.isUse;
    }
    
    public void setIsUse(int isUse) {
        this.isUse = isUse;
    }
    public Set<HotelBook> getHotelBooks() {
        return this.hotelBooks;
    }
    
    public void setHotelBooks(Set<HotelBook> hotelBooks) {
        this.hotelBooks = hotelBooks;
    }




}


