package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String adminId;
     private String password;
     private String email;
     private Timestamp registTime;
     private Timestamp updateTime;

    public Admin() {
    }

    public Admin(String adminId, String password) {
        this.adminId = adminId;
        this.password = password;
    }
    
    public Admin(String adminId, String password, String email, Timestamp registTime, Timestamp updateTime) {
       this.adminId = adminId;
       this.password = password;
       this.email = email;
       this.registTime = registTime;
       this.updateTime = updateTime;
    }
   
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Timestamp getRegistTime() {
        return this.registTime;
    }
    
    public void setRegistTime(Timestamp registTime) {
        this.registTime = registTime;
    }
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }




}


