package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private String areaId;
     private String areaName;
     private String areaImg;
//     private Set<Scenic> scenics = new HashSet<Scenic>(0);
//     private Set<FoodStore> foodStores = new HashSet<FoodStore>(0);
//     private Set<Hotel> hotels = new HashSet<Hotel>(0);

    public Areas() {
    }

	
    public Areas(String areaId) {
        this.areaId = areaId;
    }

    public Areas(String areaId, String areaName, String areaImg) {
        this.areaId = areaId;
        this.areaName = areaName;
        this.areaImg = areaImg;
    }

    public String getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }
   
//    public Set<Scenic> getScenics() {
//        return this.scenics;
//    }
//    
//    public void setScenics(Set<Scenic> scenics) {
//        this.scenics = scenics;
//    }
//    public Set<FoodStore> getFoodStores() {
//        return this.foodStores;
//    }
//    
//    public void setFoodStores(Set<FoodStore> foodStores) {
//        this.foodStores = foodStores;
//    }
//    public Set<Hotel> getHotels() {
//        return this.hotels;
//    }
//    
//    public void setHotels(Set<Hotel> hotels) {
//        this.hotels = hotels;
//    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getAreaImg() {
        return areaImg;
    }

    public void setAreaImg(String areaImg) {
        this.areaImg = areaImg;
    }




}


