package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private String hotelId;
     private Areas areas;
     private String areaName;
     private String hotelName;
     private String hotelAddress;
     private Integer hotelLike;
     private String hotelComment;
     private int isReserve;
     private String hotelImg;
     private String hotelContent;
     private Set<HotelRoom> hotelRooms = new HashSet<HotelRoom>();
     private Set<HotelBook> hotelBooks = new HashSet<HotelBook>();

    public Hotel() {
    }

	
    public Hotel(String hotelId, Areas areas, String hotelName, String hotelAddress, int isReserve) {
        this.hotelId = hotelId;
        this.areas = areas;
        this.hotelName = hotelName;
        this.hotelAddress = hotelAddress;
        this.isReserve = isReserve;
    }

    public Hotel(String hotelId, String areaName, String hotelName, String hotelAddress, Integer hotelLike, String hotelImg, String hotelContent) {
        this.hotelId = hotelId;
        this.areaName = areaName;
        this.hotelName = hotelName;
        this.hotelAddress = hotelAddress;
        this.hotelLike = hotelLike;
        this.hotelImg = hotelImg;
        this.hotelContent = hotelContent;
    }
    
    
   
    public String getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId;
    }
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public String getHotelAddress() {
        return this.hotelAddress;
    }
    
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }
    public Integer getHotelLike() {
        return this.hotelLike;
    }
    
    public void setHotelLike(Integer hotelLike) {
        this.hotelLike = hotelLike;
    }
    public String getHotelComment() {
        return this.hotelComment;
    }
    
    public void setHotelComment(String hotelComment) {
        this.hotelComment = hotelComment;
    }
    public int getIsReserve() {
        return this.isReserve;
    }
    
    public void setIsReserve(int isReserve) {
        this.isReserve = isReserve;
    }
    public String getHotelImg() {
        return this.hotelImg;
    }
    
    public void setHotelImg(String hotelImg) {
        this.hotelImg = hotelImg;
    }
    public String getHotelContent() {
        return this.hotelContent;
    }
    
    public void setHotelContent(String hotelContent) {
        this.hotelContent = hotelContent;
    }
    public Set<HotelRoom> getHotelRooms() {
        return this.hotelRooms;
    }
    
    public void setHotelRooms(Set<HotelRoom> hotelRooms) {
        this.hotelRooms = hotelRooms;
    }
    public Set<HotelBook> getHotelBooks() {
        return this.hotelBooks;
    }
    
    public void setHotelBooks(Set<HotelBook> hotelBooks) {
        this.hotelBooks = hotelBooks;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }




}


