package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

    private String noteId;
    private Users users;
    private String noteTitle;
    private int noteLike;
    private String noteImg;
    private Timestamp publishTime;
    private Timestamp updateTime;
    private String noteContent;
    private Set<NoteComment> noteComments = new HashSet<NoteComment>(0);

    public Note() {
    }

    public Note(String noteId, Users users, String noteTitle, int noteLike, String noteContent, Timestamp publishTime, Timestamp updateTime) {
        this.noteId = noteId;
        this.users = users;
        this.noteTitle = noteTitle;
        this.noteLike = noteLike;
        this.publishTime = publishTime;
        this.updateTime = updateTime;
        this.noteContent = noteContent;
    }

    public Note(String noteId, Users users, String noteTitle, int noteLike, String noteImg, Timestamp publishTime, Timestamp updateTime, String noteContent, Set<NoteComment> noteComments) {
        this.noteId = noteId;
        this.users = users;
        this.noteTitle = noteTitle;
        this.noteLike = noteLike;
        this.noteImg = noteImg;
        this.publishTime = publishTime;
        this.updateTime = updateTime;
        this.noteComments = noteComments;
        this.noteContent = noteContent;
    }

    public String getNoteId() {
        return this.noteId;
    }

    public void setNoteId(String noteId) {
        this.noteId = noteId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getNoteTitle() {
        return this.noteTitle;
    }

    public void setNoteTitle(String noteTitle) {
        this.noteTitle = noteTitle;
    }

    public int getNoteLike() {
        return this.noteLike;
    }

    public void setNoteLike(int noteLike) {
        this.noteLike = noteLike;
    }

    public String getNoteImg() {
        return noteImg;
    }

    public void setNoteImg(String noteImg) {
        this.noteImg = noteImg;
    }

    public Timestamp getPublishTime() {
        return this.publishTime;
    }

    public void setPublishTime(Timestamp publishTime) {
        this.publishTime = publishTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Set<NoteComment> getNoteComments() {
        return this.noteComments;
    }

    public void setNoteComments(Set<NoteComment> noteComments) {
        this.noteComments = noteComments;
    }

    public String getNoteContent() {
        return noteContent;
    }

    public void setNoteContent(String noteContent) {
        this.noteContent = noteContent;
    }

}
