package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * NoteComment generated by hbm2java
 */
public class NoteComment  implements java.io.Serializable {


     private String noteCommentId;
     private Note note;
     private Users users;
     private String commentContent;
     private Timestamp commentTime;

    public NoteComment() {
    }

    public NoteComment(String noteCommentId, Note note, Users users, String commentContent, Timestamp commentTime) {
       this.noteCommentId = noteCommentId;
       this.note = note;
       this.users = users;
       this.commentContent = commentContent;
       this.commentTime = commentTime;
    }
   
    public String getNoteCommentId() {
        return this.noteCommentId;
    }
    
    public void setNoteCommentId(String noteCommentId) {
        this.noteCommentId = noteCommentId;
    }
    public Note getNote() {
        return this.note;
    }
    
    public void setNote(Note note) {
        this.note = note;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public Timestamp getCommentTime() {
        return this.commentTime;
    }
    
    public void setCommentTime(Timestamp commentTime) {
        this.commentTime = commentTime;
    }




}


