package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * TourComment generated by hbm2java
 */
public class TourComment  implements java.io.Serializable {


     private String tourCommentId;
     private Tour tour;
     private Users users;
     private String commentContent;
     private Timestamp commentTime;

    public TourComment() {
    }

    public TourComment(String tourCommentId, Tour tour, Users users, String commentContent, Timestamp commentTime) {
       this.tourCommentId = tourCommentId;
       this.tour = tour;
       this.users = users;
       this.commentContent = commentContent;
       this.commentTime = commentTime;
    }
   
    public String getTourCommentId() {
        return this.tourCommentId;
    }
    
    public void setTourCommentId(String tourCommentId) {
        this.tourCommentId = tourCommentId;
    }
    public Tour getTour() {
        return this.tour;
    }
    
    public void setTour(Tour tour) {
        this.tour = tour;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public Timestamp getCommentTime() {
        return this.commentTime;
    }
    
    public void setCommentTime(Timestamp commentTime) {
        this.commentTime = commentTime;
    }




}


