package pojo;
// Generated 2018-6-8 16:29:36 by Hibernate Tools 4.3.1



/**
 * TourApply generated by hbm2java
 */
public class TourApply  implements java.io.Serializable {


     private String applyId;
     private Tour tour;
     private Users users;

    public TourApply() {
    }

    public TourApply(String applyId, Tour tour, Users users) {
       this.applyId = applyId;
       this.tour = tour;
       this.users = users;
    }
   
    public String getApplyId() {
        return this.applyId;
    }
    
    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }
    public Tour getTour() {
        return this.tour;
    }
    
    public void setTour(Tour tour) {
        this.tour = tour;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }


//select n.tour.tourId from TourApply as n where users='asd'

}


