package util;
// Generated 2018-6-8 16:29:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tour generated by hbm2java
 */
public class ConvertDate  implements java.io.Serializable {


     private String tourId;
     private String tourTitle;
     private String scenicName;
     private double tourPrice;
     private int limitNum;
     private String tripMode;
     private String hotelName;
     private int isApprove;
     private String tourBeginTime;
     private String tourEndTime;
     private String applyEndTime;
     private Set tourApplies = new HashSet(0);
     private Set tourComments = new HashSet(0);

    public ConvertDate() {
    }

	
    public ConvertDate(String tourId, String tourTitle, String scenicName, double tourPrice, int limitNum, String tripMode, String hotelName, int isApprove, String tourBeginTime, String tourEndTime, String applyEndTime) {
        this.tourId = tourId;
        this.tourTitle = tourTitle;
        this.scenicName = scenicName;
        this.tourPrice = tourPrice;
        this.limitNum = limitNum;
        this.tripMode = tripMode;
        this.hotelName = hotelName;
        this.isApprove = isApprove;
        this.tourBeginTime = tourBeginTime;
        this.tourEndTime = tourEndTime;
        this.applyEndTime = applyEndTime;
    }
    public ConvertDate(String tourId, String tourTitle, String scenicName, double tourPrice, int limitNum, String tripMode, String hotelName, int isApprove, String tourBeginTime, String tourEndTime, String applyEndTime, Set tourApplies, Set tourComments) {
       this.tourId = tourId;
       this.tourTitle = tourTitle;
       this.scenicName = scenicName;
       this.tourPrice = tourPrice;
       this.limitNum = limitNum;
       this.tripMode = tripMode;
       this.hotelName = hotelName;
       this.isApprove = isApprove;
       this.tourBeginTime = tourBeginTime;
       this.tourEndTime = tourEndTime;
       this.applyEndTime = applyEndTime;
       this.tourApplies = tourApplies;
       this.tourComments = tourComments;
    }
   
    public String getTourId() {
        return this.tourId;
    }
    
    public void setTourId(String tourId) {
        this.tourId = tourId;
    }
    public String getTourTitle() {
        return this.tourTitle;
    }
    
    public void setTourTitle(String tourTitle) {
        this.tourTitle = tourTitle;
    }
    public String getScenicName() {
        return this.scenicName;
    }
    
    public void setScenicName(String scenicName) {
        this.scenicName = scenicName;
    }
    public double getTourPrice() {
        return this.tourPrice;
    }
    
    public void setTourPrice(double tourPrice) {
        this.tourPrice = tourPrice;
    }
    public int getLimitNum() {
        return this.limitNum;
    }
    
    public void setLimitNum(int limitNum) {
        this.limitNum = limitNum;
    }
    public String getTripMode() {
        return this.tripMode;
    }
    
    public void setTripMode(String tripMode) {
        this.tripMode = tripMode;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public int getIsApprove() {
        return this.isApprove;
    }
    
    public void setIsApprove(int isApprove) {
        this.isApprove = isApprove;
    }
    public String getTourBeginTime() {
        return this.tourBeginTime;
    }
    
    public void setTourBeginTime(String tourBeginTime) {
        this.tourBeginTime = tourBeginTime;
    }
    public String getTourEndTime() {
        return this.tourEndTime;
    }
    
    public void setTourEndTime(String tourEndTime) {
        this.tourEndTime = tourEndTime;
    }
    public String getApplyEndTime() {
        return this.applyEndTime;
    }
    
    public void setApplyEndTime(String applyEndTime) {
        this.applyEndTime = applyEndTime;
    }
    public Set getTourApplies() {
        return this.tourApplies;
    }
    
    public void setTourApplies(Set tourApplies) {
        this.tourApplies = tourApplies;
    }
    public Set getTourComments() {
        return this.tourComments;
    }
    
    public void setTourComments(Set tourComments) {
        this.tourComments = tourComments;
    }




}


