package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * FoodStoreComment generated by hbm2java
 */
public class FoodStoreComment  implements java.io.Serializable {


     private String storeCommentId;
     private FoodStore foodStore;
     private Users users;
     private String commentContent;
     private Timestamp commentTime;

    public FoodStoreComment() {
    }

    public FoodStoreComment(String storeCommentId, FoodStore foodStore, Users users, String commentContent, Timestamp commentTime) {
       this.storeCommentId = storeCommentId;
       this.foodStore = foodStore;
       this.users = users;
       this.commentContent = commentContent;
       this.commentTime = commentTime;
    }
   
    public String getStoreCommentId() {
        return this.storeCommentId;
    }
    
    public void setStoreCommentId(String storeCommentId) {
        this.storeCommentId = storeCommentId;
    }
    public FoodStore getFoodStore() {
        return this.foodStore;
    }
    
    public void setFoodStore(FoodStore foodStore) {
        this.foodStore = foodStore;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCommentContent() {
        return this.commentContent;
    }
    
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }
    public Timestamp getCommentTime() {
        return this.commentTime;
    }
    
    public void setCommentTime(Timestamp commentTime) {
        this.commentTime = commentTime;
    }




}


