package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * HotelBook generated by hbm2java
 */
public class HotelBook  implements java.io.Serializable {
     private String bookId;
     private Hotel hotel;
     private HotelRoom hotelRoom;
     private Users users;
     private Timestamp checkInTime;
     private Timestamp checkOutTime;

    public HotelBook() {
    }

    public HotelBook(String bookId, Hotel hotel, HotelRoom hotelRoom, Users users, Timestamp checkInTime, Timestamp checkOutTime) {
       this.bookId = bookId;
       this.hotel = hotel;
       this.hotelRoom = hotelRoom;
       this.users = users;
       this.checkInTime = checkInTime;
       this.checkOutTime = checkOutTime;
    }
   
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public HotelRoom getHotelRoom() {
        return this.hotelRoom;
    }
    
    public void setHotelRoom(HotelRoom hotelRoom) {
        this.hotelRoom = hotelRoom;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Timestamp getCheckInTime() {
        return this.checkInTime;
    }
    
    public void setCheckInTime(Timestamp checkInTime) {
        this.checkInTime = checkInTime;
    }
    public Timestamp getCheckOutTime() {
        return this.checkOutTime;
    }
    
    public void setCheckOutTime(Timestamp checkOutTime) {
        this.checkOutTime = checkOutTime;
    }


}


