package pojo;
// Generated 2018-5-28 23:08:24 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * Notification generated by hbm2java
 */
public class Notification  implements java.io.Serializable {


     private String notifyId;
     private Users users;
     private String notifyContent;
     private Timestamp sendTime;

    public Notification() {
    }

    public Notification(String notifyId, Users users, String notifyContent, Timestamp sendTime) {
       this.notifyId = notifyId;
       this.users = users;
       this.notifyContent = notifyContent;
       this.sendTime = sendTime;
    }
   
    public String getNotifyId() {
        return this.notifyId;
    }
    
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNotifyContent() {
        return this.notifyContent;
    }
    
    public void setNotifyContent(String notifyContent) {
        this.notifyContent = notifyContent;
    }
    public Timestamp getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Timestamp sendTime) {
        this.sendTime = sendTime;
    }




}


